Repository prgrms-fe-devcourse/FES-5-Project2-TEAM-5, pull requests merged in 2025-07, with the labels that each got.

#24 fix: 중복된 package.json 중복 의존성 삭제
  package.json
  src/assets/logo.png
  src/assets/logo.svg
  src/pages/auth/Login/index.tsx
Labels: feature

#42 feat: 회원가입 시 email users 테이블에 저장
  src/pages/auth/Register/index.tsx
  src/pages/auth/Register/utils/helper.ts
Labels: feature

#60 style: 스타일 피드백 적용
  src/pages/Home/components/Chat/style.module.css
  src/pages/Home/style.module.css
Labels: UI

#85 Feature/77 empty diary style
  src/pages/analysis/EmotionAndQuest/index.tsx
  src/pages/analysis/SelectDiary/components/NextPageButton/index.tsx
  src/pages/analysis/SelectDiary/components/NextPageButton/style.module.css
  src/pages/analysis/SelectDiary/index.tsx
  src/pages/analysis/SelectDiary/style.module.css
  src/pages/analysis/SelectDiary/utils/date.ts
  src/shared/components/Spinner/index.tsx
  src/shared/components/Spinner/style.module.css
Labels: refactor, UI

#83 Feature/70 GitHub login implement
  src/App.tsx
  src/pages/Home/components/MessageItem/style.module.css
  src/pages/Mypage/components/ChangeProfile/style.module.css
  src/pages/Mypage/components/UserInfoSection/style.module.css
  src/pages/auth/AuthCallback/index.tsx
  src/pages/auth/Login/index.tsx
  src/pages/auth/components/AuthLayout/style.module.css
  src/shared/api/auth.ts
  src/shared/api/supabase/client.ts
  src/shared/api/user.ts
  src/shared/components/Header/index.tsx
  src/shared/components/Header/style.module.css
  src/shared/components/ProtectedLayout/index.tsx
  src/shared/constants/path.ts
  src/shared/context/UserContext.tsx
  src/shared/hoc/withConditionalRender.tsx
  src/shared/hooks/useUser.ts
Labels: feature

#90 fix: 로그인 상태 관리 버그 수정 원인: onAuthStateChange 콜백 함수 내에서 호출한 서버 통신 및 setter 함수 호출로 react rendering 시스템과 충돌로인해 supabase api 통신이 에러도 뱉지않고 무한 기다림 발생
  src/shared/hooks/useUser.ts
Labels: bug

#104 Feature/96 alarm implement
  src/shared/api/notification.ts
  src/shared/api/supabase/client.ts
  src/shared/api/supabase/types.ts
  src/shared/components/Header/index.tsx
  src/shared/components/Header/style.module.css
  src/shared/components/Notification/components/NotificationItem/index.tsx
  src/shared/components/Notification/components/NotificationItem/style.module.css
  src/shared/components/Notification/hook/useNotification.ts
  src/shared/components/Notification/index.tsx
  src/shared/components/Notification/style.module.css
Labels: feature, UI

#109 feat: quest UI & 기능 구현
  src/pages/Home/components/Molly/index.tsx
  src/pages/Home/components/QuestSection/components/QuestItem/index.tsx
  src/pages/Home/components/QuestSection/components/QuestItem/style.module.css
  src/pages/Home/components/QuestSection/index.tsx
  src/pages/Home/components/QuestSection/style.module.css
  src/pages/Home/index.tsx
  src/pages/Home/style.module.css
  src/shared/api/chat.ts
  src/shared/api/quest.ts
  src/shared/types/quest.ts
  src/shared/utils/dateUtils.ts
Labels: feature, UI

#115 feat: 알림 UI 수정 완료
  src/shared/components/Notification/components/NotificationItem/index.tsx
  src/shared/components/Notification/components/NotificationItem/style.module.css
  src/shared/components/Notification/index.tsx
  src/shared/components/Notification/style.module.css
Labels: UI

#117 style: 헤더 메뉴 indicator 적용
  src/shared/components/Header/index.tsx
  src/shared/components/Header/style.module.css
Labels: UI

#120 feat: user에 따른 일기장 상세 변화
  src/pages/Diary/DiaryDetail/index.tsx
  src/pages/Diary/DiaryDetail/style.module.css
Labels: feature, UI

#121 feat: 404 페이지 적용
  src/App.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.module.css
  src/shared/constants/path.ts
  src/shared/hoc/withConditionalRender.tsx
Labels: feature

#123 feat: 퀘스트 목록 버그 수정
  src/pages/Home/components/QuestSection/components/QuestItem/style.module.css
  src/pages/Home/components/QuestSection/index.tsx
  src/pages/Home/components/QuestSection/style.module.css
  src/shared/components/Notification/style.module.css
  src/shared/hoc/withConditionalRender.tsx
  src/shared/utils/dateUtils.ts
Labels: bug
